project/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('second', secondpage, name="secondpage"),
    path('new-post', new_post, name="new-post"),
    path('create', create, name="create"),
    path('<int:id>', detail, name="detail"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('tag-list', tag_list, name="tag-list"),
    path('tag-posts/<int:tag_id>', tag_posts, name="tag-posts"),
    path('likes/<int:post_id>', likes, name="likes")
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('mypage/<int:id>', mypage, name="mypage"),
    path('follow/<int:id>', follow, name="follow"),
]

project/users/models.py
from django.db import models

# Create your models here.

project/users/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib import auth
from main.models import Post
from django.contrib.auth.models import User
# Create your views here.
def mypage(request, id):
    user = get_object_or_404(User, pk=id)
    followers = user.profile.followers.all()
    followings = user.profile.followings.all()

    context = {
        'target_user':user,
        'followers': followers,
        'followings': followings,
    }
    return render(request, 'users/mypage.html', context)

def follow(request, id):
    user = request.user
    followed_user = get_object_or_404(User, pk=id)
    is_follower=user.profile in followed_user.profile.followers.all()
    if is_follower:
        user.profile.followings.remove(followed_user.profile)
    else:
        user.profile.followings.add(followed_user.profile)
    return redirect('users:mypage', followed_user.id)

project/users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div>

    <h1>마이페이지에 오신 것을 환영합니다</h1>
</div>

<div>
    User : {{target_user}} <br>
    UserProfile : {{target_user.profile}} <br>

<p>팔로워<br>{{ target_user.profile.followers.count}}명</p>
<ul>
    {% for follower in followers %}
    <li><a href="{% url 'users:mypage' follower.user.id %}">{{ follower.user.username }}</a></li>

    {% endfor %}
</ul>

<p>팔로잉<br>{{ target_user.profile.followings.count}}명</p>
<ul>
    {% for following in followings %}
    <li><a href="{% url 'users:mypage' following.user.id %}">{{ following.user.username }}</a></li>
    {% endfor %}
</ul>


{% if request.user != target_user %}
    {% if request.user.profile in target_user.profile.followers.all %}
        <a href="{% url 'users:follow' target_user.id %}">
        <button type="button" class="btn btn-outline-info">언팔로우</button>
        </a>
    {% else %}
        <a href="{% url 'users:follow' target_user.id %}">
        <button type="button" class="btn btn-info">팔로우</button>
        </a>
        {% endif %}
    {% endif %}
</div>


<div>
    {% for post in posts %}
    <div>
        <hr/>
        <h3>{{post.title}}</h3>
        {{post.writer}} | {{post.weather}} | {{post.pub_date}}<br>
        {{post.summary}}
        <a href="{% url 'main:detail' post.id %}">자세히 보기</a>
        <br>
    </div>
    {% endfor %}  
</div>
{% endblock %}