project/accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"
urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('signup/', signup, name="signup"),
]

project/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('second', secondpage, name="secondpage"),
    path('new-post', new_post, name="new-post"),
    path('create', create, name="create"),
    path('<int:id>', detail, name="detail"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('tag-list', tag_list, name="tag-list"),
    path('tag-posts/<int:tag_id>', tag_posts, name="tag-posts"),
    path('likes/<int:post_id>', likes, name="likes")
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('mypage/<int:id>', mypage, name="mypage"),
    path('follow/<int:id>', follow, name="follow"),
]

project/project/templates/shared/_navbar.html
<nav class="navbar-container">
    <!-- mainpage 링크 연결 -->
    <a class="navbar-link" href="{% url 'main:mainpage' %}">DGU_likelion_12th</a> 
    <!-- secondpage 링크 연결 -->
    <a class="navbar-link" href="{% url 'main:secondpage' %}">Second Page</a>

    <a class="navbar-link" href="{% url 'main:tag-list' %}">Tag</a>

    <div class="nav-right">
      {% if user.is_authenticated %}
      <ul class="nav-link-account">
        <li class="nav-link-user">{{user.username}}</li>
        <li><a href="{% url 'accounts:logout' %}">로그아웃</a></li>
        <li><a href="{% url 'users:mypage' user.id %}">mypage</a></li>
      </ul>
      {% else %}
      <ul class="nav-link-account">
        <li><a href="{% url 'accounts:login' %}">로그인</a></li>
        <li><a href="{% url 'accounts:signup' %}">signup</a></li>
      </ul>
      {% endif %}
    </div>
  </nav>