project/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('second', secondpage, name="secondpage"),
    path('new-post', new_post, name="new-post"),
    path('create', create, name="create"),
    path('<int:id>', detail, name="detail"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('tag-list', tag_list, name="tag-list"),
    path('tag-posts/<int:tag_id>', tag_posts, name="tag-posts"),
    path('likes/<int:post_id>', likes, name="likes")
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('mypage/<int:id>', mypage, name="mypage"),
    path('follow/<int:id>', follow, name="follow"),
]

project/main/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, blank=False)

    def __str__(self):
        return self.name



class Post(models.Model):
    title = models.CharField(max_length=50)
    writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    weather = models.CharField(max_length=20)
    body = models.TextField()
    pub_date = models.DateTimeField()
    image = models.ImageField(upload_to="post/", blank=True, null=True)
    tags = models.ManyToManyField(Tag, related_name='posts', blank=True)
    like = models.ManyToManyField(User, related_name='likes', blank=True)
    like_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:20]
    
class Comment(models.Model):
    content = models.TextField()
    pub_date = models.DateTimeField()
    writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, null=False, blank=False, on_delete=models.CASCADE)

    def __str__(self):
        return self.post.title + " : " + self.content[:20] + " by " + self.writer.profile.nickname

project/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from .models import Post, Comment, Tag

# Create your views here.
def mainpage(request):
    return render(request, 'main/mainpage.html')

def secondpage(request):
    posts = Post.objects.all()
    return render(request, 'main/secondpage.html', {'posts': posts})

def new_post(request):
    return render(request, 'main/new-post.html')

def detail(request, id):
    post = get_object_or_404(Post, pk=id)
    comments = Comment.objects.filter(post=post)

    if request.method == 'POST':
        if 'delete_comment_id' in request.POST:
            comment_id = request.POST['delete_comment_id']
            comment = get_object_or_404(Comment, id=comment_id)
            if request.user.is_authenticated and comment.writer == request.user:
                comment.delete()
                return redirect('main:detail', id=id)  # 리다이렉트를 redirect 함수로 처리

        elif request.user.is_authenticated:
            new_comment = Comment()
            new_comment.post = post
            new_comment.writer = request.user
            new_comment.content = request.POST['content']
            new_comment.pub_date = timezone.now()
            new_comment.save()
            return redirect('main:detail', id=id)  # 리다이렉트를 redirect 함수로 처리

        else:
            return redirect('accounts:login')

    return render(request, 'main/detail.html', {'post': post, 'comments': comments})

def edit(request, id):
    edit_post = Post.objects.get(pk=id)
    return render(request, 'main/edit.html', {'post' : edit_post})

def create(request):
    if request.user.is_authenticated:
        new_post = Post()

        new_post.title = request.POST['title']
        new_post.writer = request.user
        new_post.weather = request.POST['weather']
        new_post.body = request.POST['body']
        new_post.pub_date = timezone.now()
        new_post.image = request.FILES.get('image')

        new_post.save()

        words = new_post.body.split(' ')
        tag_list = []

        for w in words:
            if len(w)>0:
                if w[0] == '#':
                    tag_list.append(w[1:])
        
        for t in tag_list:
            tag, boolean = Tag.objects.get_or_create(name=t)
            new_post.tags.add(tag.id)

        return redirect('main:detail', new_post.id)
    
    else:
        return redirect('accounts:login')

def update(request, id):
    update_post = Post.objects.get(pk=id)
    if request.user.is_authenticated and request.user == update_post.writer:
        update_post.title = request.POST['title']
        update_post.weather = request.POST['weather']
        update_post.body = request.POST['body']
        update_post.pub_date = timezone.now()

        if request.FILES.get('image'):
            update_post.image = request.FILES['image']

        update_post.save()
        return redirect('main:detail', update_post.id)
    return redirect('accounts:login', update_post.id)


def delete(request, id):
    delete_post = Post.objects.get(pk=id)
    delete_post.delete()
    return redirect('main:secondpage')


def tag_list(request):
    tags = Tag.objects.all()
    return render(request, 'main/tag-list.html', {'tags' : tags })

def tag_posts(request, tag_id):
    tag = get_object_or_404(Tag, id=tag_id)
    posts = tag.posts.all()
    return render(request, 'main/tag-post.html', {
        'tag' : tag,
        'posts' : posts
    })

def likes(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user in post.like.all():
        post.like.remove(request.user)
        post.like_count -=1
        post.save()
    else:
        post.like.add(request.user)
        post.like_count += 1
        post.save()
    return redirect('main:detail', post.id)

project/main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>{{post.title}}</h3>
<a href="{% url 'users:mypage' post.writer.id %}">작성자 : {{post.writer}}</a>
날씨 : {{post.weather}}
날짜 : {{post.pub_date}}
<a href="{% url 'main:likes' post.id %}">
    {% if user in post.like.all %} 취소 {% else %} 좋아요 {% endif %}
</a>
{{post.like_count}}개
<p>
    {% for tag in post.tags.all %}
            <a href="{% url 'main:tag-posts' tag.id %}">#{{ tag.name }} </a>
    {% endfor %}
</p>
<hr/>
{% if post.image %}
<p><img src="{{ post.image.url }}" alt="사진" width="100px"></p>
{% endif %}
<p>{{post.body}}</p>

{% if post.writer == user %}
<a href="{% url 'main:edit' post.id %}">글 수정하기</a>
<a href="{% url 'main:delete' post.id %}">삭제하기</a>
{% endif %}
<br>
<div class="comment_container">
    <div class="comment_form">
        <h2></h2>
        <form action="{% url 'main:detail' post.id %}" method="POST">
            {% csrf_token %}
            댓글 쓰기 : <input type="text" name="content">
            <input type="submit" name="submit">
        </form>
    </div>
    <div class="comment_list">
        {% for comment in comments %}
        <hr>
        <h4>작성자 : {{comment.writer}}</h4>
        <p>내용 : {{comment.content}}</p>
        <p>{{comment.pub_date}}</p>
        {% if user.is_authenticated and comment.writer == user %}
            <form action="{% url 'main:detail' post.id %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="delete_comment_id" value="{{ comment.id }}">
                <button type="submit">댓글 삭제</button>
            </form>
        {% endif %}
        {% endfor %}
    </div>
{% endblock %}

project/main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>수정중...</h2>
<form action="{% url 'main:update' post.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>제목 : <input type="text" name="title" value="{{post.title}}"></p>
    <p>작성자 : <input type="text" name="writer" value="{{post.writer}}"></p>
    <p>날씨 : <input type="text" name="weather" value="{{post.weather}}"></p>
    {% if post.image %}
        <p><img src="{{ post.image.url }}" alt="사진" width="100px"></p>
    {% endif %}
    <p>사진 : <input type="file" name="image"></p>
    <p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10">{{post.body}}</textarea></p>
    <button type="submit">제출</button>
</form>
{% endblock %}

project/main/templates/main/firstpage.html
    {% extends 'base.html' %}

    {% block content %}
    <h1 class="contents">2024 멋쟁이사자처럼 12기</h1>
    <div class="contents">Django MTV 내용정리</div>
    <div class="footer-content">💡Django MTV 패턴이란?
      <ul>
        <p>1️⃣Request(URL)</p>
        <p>2️⃣URL Conf(url, view 매핑)</p>
        <p>3️⃣View:요청에 따른 적절한 로직 수행</p>
        <p>4️⃣Model:데이터</p>
        <p>5️⃣Template:보여지는 부분,인터페이스</p>
        <p>6️⃣Response</p>
      </ul>
    </div>
    <div class="footer-content">HTML 페이지
      <ul>
        <p>1️⃣mainpage 주세요! request(URL)</p>
        <p>2️⃣urls.py</p>
        <p>3️⃣views.py</p>
        <p>4️⃣짠! mainpage.html response</p>        
      </ul>
    </div>
    <div class="footer-content">템플릿(template) 언어
      <ul>
        <p>파이썬의 변수, 문법을 HTML에서 사용할 수 있도록 제공하는 직관적인 언어</p>
        <li>변수➡&lbrace;&lbrace;변수명&rbrace;&rbrace; </li>
        <li>변수의 속성➡&lbrace;&lbrace;변수명.속성명&rbrace;&rbrace; </li>
        <li>list의 각 인덱스➡&lbrace;&lbrace;list.index&rbrace;&rbrace;</li>
        <li>dict의 key값➡&lbrace;&lbrace;dict.key&rbrace;&rbrace; </li>       
      </ul>
      <ul>
        <li>조건문 형태 &lbrace;% if %&rbrace; &lbrace;% else %&rbrace; &lbrace;% endif %&rbrace; </li>
        <li>반복문 형태 &lbrace;% for num in nums %&rbrace; &lbrace;&lbrace; num &rbrace;&rbrace; &lbrace;% endfor %&rbrace; </li>
        <li>템플릿 필터 &lbrace;&lbrace; 변수명|필터 &rbrace;&rbrace; </li>
        <li>템플릿 주석 &lbrace;# 주석 #&rbrace; </li>
      </ul>
    </div>
    <div class="footer-content">템플릿 상속, nav bar 분리
      <ul>
        <p>반복되는 코드 상속하기</p>
        <li>project 폴더 내, templates 폴더 + base.html생성</li>
        <li>&lbrace;%block content%&rbrace; : 재사용 가능한 블록 범위를 정의</li>
        <li>&lbrace;%endblock%&rbrace; : 블록의 끝</li>
        <li>&lbrace;%extends 'base.html%&rbrace; : 업데이트</li> 
        <li>장고가 base.html의 경로를 찾을 수 있게 설정</li>     
      </ul>
    </div>
    <div class="footer-content">Static
      <ul>
        <p>웹 페이지에서 사용되는 정적인 파일을 저장하는 디렉토리리</p>
        <p>1️⃣project 폴더 안에 static 폴더 만들기</p>
        <p>2️⃣static 폴더 안에 images, css 폴더 만들기</p>
        <p>3️⃣css 폴더 내에 project.css 파일 만들기</p>
        <li>생성한 폴더/파일에 내용 추가</li> 
        <li>&lbrace; load static &rbrace;➡ HTML 파일에서 활용 </li> 
        <li>경로 설정 settings.py </li>         
      </ul>
    </div>
    {% endblock %}

project/main/templates/main/mainpage.html
    {% extends 'base.html' %}

    {% block content %}
    <h1 class="contents">2024 멋쟁이사자처럼 12기</h1>
    <div class="contents">Django MTV 내용정리</div>
    <div class="footer-content">💡Django MTV 패턴이란?
      <ul>
        <p>1️⃣Request(URL)</p>
        <p>2️⃣URL Conf(url, view 매핑)</p>
        <p>3️⃣View:요청에 따른 적절한 로직 수행</p>
        <p>4️⃣Model:데이터</p>
        <p>5️⃣Template:보여지는 부분,인터페이스</p>
        <p>6️⃣Response</p>
      </ul>
    </div>
    <div class="footer-content">HTML 페이지
      <ul>
        <p>1️⃣mainpage 주세요! request(URL)</p>
        <p>2️⃣urls.py</p>
        <p>3️⃣views.py</p>
        <p>4️⃣짠! mainpage.html response</p>        
      </ul>
    </div>
    <div class="footer-content">템플릿(template) 언어
      <ul>
        <p>파이썬의 변수, 문법을 HTML에서 사용할 수 있도록 제공하는 직관적인 언어</p>
        <li>변수➡&lbrace;&lbrace;변수명&rbrace;&rbrace; </li>
        <li>변수의 속성➡&lbrace;&lbrace;변수명.속성명&rbrace;&rbrace; </li>
        <li>list의 각 인덱스➡&lbrace;&lbrace;list.index&rbrace;&rbrace;</li>
        <li>dict의 key값➡&lbrace;&lbrace;dict.key&rbrace;&rbrace; </li>       
      </ul>
      <ul>
        <li>조건문 형태 &lbrace;% if %&rbrace; &lbrace;% else %&rbrace; &lbrace;% endif %&rbrace; </li>
        <li>반복문 형태 &lbrace;% for num in nums %&rbrace; &lbrace;&lbrace; num &rbrace;&rbrace; &lbrace;% endfor %&rbrace; </li>
        <li>템플릿 필터 &lbrace;&lbrace; 변수명|필터 &rbrace;&rbrace; </li>
        <li>템플릿 주석 &lbrace;# 주석 #&rbrace; </li>
      </ul>
    </div>
    <div class="footer-content">템플릿 상속, nav bar 분리
      <ul>
        <p>반복되는 코드 상속하기</p>
        <li>project 폴더 내, templates 폴더 + base.html생성</li>
        <li>&lbrace;%block content%&rbrace; : 재사용 가능한 블록 범위를 정의</li>
        <li>&lbrace;%endblock%&rbrace; : 블록의 끝</li>
        <li>&lbrace;%extends 'base.html%&rbrace; : 업데이트</li> 
        <li>장고가 base.html의 경로를 찾을 수 있게 설정</li>     
      </ul>
    </div>
    <div class="footer-content">Static
      <ul>
        <p>웹 페이지에서 사용되는 정적인 파일을 저장하는 디렉토리리</p>
        <p>1️⃣project 폴더 안에 static 폴더 만들기</p>
        <p>2️⃣static 폴더 안에 images, css 폴더 만들기</p>
        <p>3️⃣css 폴더 내에 project.css 파일 만들기</p>
        <li>생성한 폴더/파일에 내용 추가</li> 
        <li>&lbrace; load static &rbrace;➡ HTML 파일에서 활용 </li> 
        <li>경로 설정 settings.py </li>         
      </ul>
    </div>
    {% endblock %}

project/main/templates/main/new-post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form action="{% url 'main:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>제목 : <input type="text" name="title"></p>
    <!-- <p>작성자 : <input type="text" name="writer"></p> -->
    <p>날씨: <input type="text" name="weather"></p>
    <p>사진 : <input type="file" name="image"></p>
    <p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10"></textarea></p>
    <button type="submit">제출</button>
</form>

{% endblock %}

project/main/templates/main/secondpage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div>
  <img src="{% static 'images/logo.png' %}" alt="logo" width="300px">
  <div class="contents">This is Second Page</div>
  <div class="contents">I Love Teddy Bear♥ </div>
</div>    
<div>
  <div>
    {% if user.is_authenticated %}
    <a href="{% url 'main:new-post' %}">새 글 작성하기</a>
    {% endif %}
  </div>
  {% for post in posts %}
  <div>
    <hr/>
    <h3>{{post.title}}</h3>
    {{post.writer}} | {{post.weather}} | {{post.pub_date}}<br>
    {{post.summary}}
    <a href="{% url 'main:detail' post.id %}">자세히 보기</a>
    <br>
  </div>
  {% endfor %}  
</div>
{% endblock %}

project/main/templates/main/tag-list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h1>해시태그 목록</h1>
    <hr>
    {% for t in tags %}
    <div>
        <h2><a href="{% url 'main:tag-posts' t.id %}">#{{t.name}}</a></h2>
    </div>
    {% endfor %}
</div>

{% endblock %}

project/main/templates/main/tag-post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h1>#{{tag}}가 달린 게시글</h1>
    <hr>
    <div>
        {% for p in posts %}
        <hr/>
        <h3>{{p.title}}</h3>
        {{p.writer}} | {{p.pub_date}}<br>
        {{p.summary}}
        <a href="{% url 'main:detail' p.id %}">자세히 보기</a>
        <br>
        {% endfor %}
    </div>
</div>

{% endblock %}